version: '3.6'

volumes:
    dev-shared:

services:
# -------------=== Rest api ===-------------
  sawtooth-rest-api-0:
    container_name: rest-api-0
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8100:8008'
    depends_on:
      - validator-0
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator-0:4004
        --bind sawtooth-rest-api-0:8008
  sawtooth-rest-api-1:
    container_name: rest-api-1
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8200:8008'
    depends_on:
      - validator-1
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator-1:4004
        --bind sawtooth-rest-api-1:8008
  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator-0
    command: settings-tp -vv --connect tcp://validator-0:4004
  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator-1
    command: settings-tp -vv --connect tcp://validator-1:4004
  validator-0:
    container_name: validator-0
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
      - 8800
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator-0:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --peering static \
          --peers tcp://validator-1:8800 \
          --scheduler serial \
          --network-auth trust
      "
  validator-1:
    container_name: validator-1
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
      - 8800
    depends_on:
      - validator-0
    command: |
      bash -c "
       if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        mkdir -p /keys/validator-1 || true && \
        cp -a /root/.sawtooth/keys /keys/validator-1/ && \
        echo '--- Validator setup completed... ---\n'
      else
        echo '----Validator setup skipped.....\n'
      fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --peering static \
          --scheduler serial \
          --network-auth trust
      "