
version: '2.1'

services:
# -------------=== Client / shell ===-------------
  equity-tokenization-client:
    container_name: equity-tokenization-client
    build:
      context: .
      dockerfile: ./jsclient/Dockerfile
    volumes:
      - '.:/project/equity-tokenization/'
    ports:
      - '0.0.0.0:3000:3000'

# -------------=== Transaction processor ===-------------
  equity-tokenization-tp:
    container_name: equity-tokenization-tp
    build:
        context: .
        dockerfile: ./jsprocessor/Dockerfile
    volumes:
        - '.:/project/equity-tokenization/'
    expose:
        - 4004
    command: node index.js tcp://validator:4004 -vv -C tcp://validator:4004
    stop_signal: SIGKILL

# -------------=== Rest api ===-------------
  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind rest-api-0:8008

# -------------=== Settings tp ===-------------
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

# -------------=== Validators ===-------------
  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
